In [1]:
import numpy as np

In [2]:
Car_attributes = [[10,23,45,65,12],[231,231,212,432,323],[345,342,344,543,453]]

In [4]:
Car_attributes_arr = np.array(Car_attributes,dtype = 'float')

In [5]:
print(Car_attributes_arr)

[[ 10.  23.  45.  65.  12.]
 [231. 231. 212. 432. 323.]
 [345. 342. 344. 543. 453.]]


In [6]:
print(Car_attributes_arr.dtype)

float64
